### PR TITLE
Added mouse event support to Gate

### PR DESCRIPTION
**Pull request by JWorthe**
Hi Matthew,

I hope this message finds you well. I found your Gate engine based on a tweet you sent out a while back, showing that platformer demo.

I've been digging through your code as a learning experience for myself, and I've really been liking how the whole thing's structured. I'm a big fan of Rust, and have been fiddling with WebAssembly in my spare time, so seeing a simple game engine in Rust that targets WebAssembly was something I was really interested in.

I decided to try my hand at using Gate to build a simple game of my own, but quickly ran into the issue that I wanted to use the mouse for input but there weren't any mouse events. I've added the mouse support on my own fork to see how it worked out. I know this is a bit out of the blue, but since I've done it now I thought I may as well offer the changes back in case you find them useful. I promise I won't take it personally if you completely restructure / reimplement / discard the stuff here.

In terms of design decisions, I refactored your keyboard event from two variables, KeyEvent and KeyCode which were passed around together, to an InputEvent enum. KeyPressed and KeyReleased are now InputEvents which contain a KeyCode. This is unfortunately a breaking change for client code, but was necessary to allow the MousePressed MouseReleased and MouseMotion events to have their own mousy data.

The other weird thing I had to do was involve the renderer in the input events. I'm admittedly a bit uncomfortable with this, but it was necessary to convert the x and y coordinates coming in from SDL / the browser from the coordinate system of the window to the coordinate system of the game. Only the renderer seemed to know the details of the window coordinates in order to do this transformation. The plus side is that by the time you get up to your game code, the mouse events have an x and y that are entirely in the game's internal coordinate system.

I'd love to hear your input and how you would have gone about this change.

Kind regards,
Justin

### CODE REVIEW

**Comment by SergiusIW** [comment]
Hi Justin,

Thanks for sharing, and glad you liked the code! I was actually planning to add the mouse events at some point, probably within the next couple of months, for use in a project I have been working on. I haven't given much thought to the API yet, but I think I might create a second input method in `App` for the mouse events, rather than reworking `KeyEvent`. We'll see. I'll get back to you later.

-Matthew

**Comment by JWorthe** [comment]
Thanks Matthew. Yes, I can see how a second function in App for mouse events would work well. I'm interested to see how it turns out when you get to it.

Cheers for now,
Justin

**Comment by SergiusIW** [comment]
Hi Justin! I just finished implementing mouse events, and pushed out version 0.4.0 of Gate. My approach to this API is a little non-standard, but I think it unifies the API nicely. First, I replaced the `Audio` object that was being passed around with a more general `AppContext` object. Along with being able to perform audio playback, this `AppContext` can tell you the app dimensions and the mouse cursor position. Then, I made mouse click/release events behave exactly the same as keyboard events, so there is now `KeyCode::MouseLeft`/`MouseMiddle`/`MouseRight`. Since you can get the cursor position from the `AppContext`, there is no reason to repeat that information in the mouse event. I did end up looking at some of your code for reference, it was helpful. But I will be closing this pull request now.

Kind regards,
-Matthew

**Comment by JWorthe** [comment]
Thanks for the feedback Matthew. I'm glad you found my code useful. I like the `AppContext` approach. It will work much better than my idea if you want to trigger something at the cursor using the keyboard.

Kind regards,
Justin

**Pull request closed without merging**
